services:
  - type: worker
    name: btc-momentum-bot
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
